name: Build and test
on:
  pull_request: { }
  workflow_call: { }
jobs:
  build-and-test:
    name: Run tests on ${{ matrix.os }}
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java environment
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 11

      - name: Build
        id: build
        run: mvn -B -U "-Dsurefire.rerunFailingTestsCount=5" clean install

      - name: Archive Test Results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Unit Test Results ${{ matrix.os }}
          path: "*/target/surefire-reports/"
          retention-days: 7

# We need to upload the event file as an artifact in order to support publishing the results of
# forked repositories (https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches)
  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Event File
          path: ${{ github.event_path }}
          retention-days: 1
